# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(959, 667)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.listWidget = QtGui.QListWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(190, 200))
        self.listWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listWidget.setAutoFillBackground(True)
        self.listWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.listWidget.setIconSize(QtCore.QSize(60, 60))
        self.listWidget.setMovement(QtGui.QListView.Free)
        self.listWidget.setFlow(QtGui.QListView.TopToBottom)
        self.listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget.setGridSize(QtCore.QSize(100, 60))
        self.listWidget.setViewMode(QtGui.QListView.ListMode)
        self.listWidget.setBatchSize(150)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        font.setItalic(False)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/superpose.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/shapeup.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/she.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/pregxs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        item.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/retrieval.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(460, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(17)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_3.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 959, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(60, 60))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.statusBar.setWhatsThis(_fromUtf8(""))
        self.statusBar.setAccessibleName(_fromUtf8(""))
        self.statusBar.setAutoFillBackground(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuit.setIcon(icon5)
        self.actionQuit.setPriority(QtGui.QAction.HighPriority)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionPymol = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/pymol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPymol.setIcon(icon7)
        self.actionPymol.setObjectName(_fromUtf8("actionPymol"))
        self.actionPreference = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreference.setIcon(icon8)
        self.actionPreference.setObjectName(_fromUtf8("actionPreference"))
        self.actionEmail_help = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/email_help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEmail_help.setIcon(icon9)
        self.actionEmail_help.setObjectName(_fromUtf8("actionEmail_help"))
        self.actionSASTBX = QtGui.QAction(MainWindow)
        self.actionSASTBX.setObjectName(_fromUtf8("actionSASTBX"))
        self.actionDocument = QtGui.QAction(MainWindow)
        self.actionDocument.setObjectName(_fromUtf8("actionDocument"))
        self.actionOpenProject = QtGui.QAction(MainWindow)
        self.actionOpenProject.setObjectName(_fromUtf8("actionOpenProject"))
        self.actionPymol_2 = QtGui.QAction(MainWindow)
        self.actionPymol_2.setObjectName(_fromUtf8("actionPymol_2"))
        self.menu_File.addAction(self.actionOpenProject)
        self.menu_Help.addAction(self.actionSASTBX)
        self.menu_Help.addAction(self.actionDocument)
        self.menuEdit.addAction(self.actionPymol_2)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionPymol)
        self.toolBar.addAction(self.actionPreference)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionEmail_help)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SASTBX", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Model Superposition", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Shape Search Engine", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Intensity Calculation", None))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "P(r) Estimation", None))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Protein Retrieval Engine", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Active Project", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status", None))
        self.label.setText(_translate("MainWindow", "Current Project", None))
        self.pushButton.setText(_translate("MainWindow", "Brower", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionQuit.setText(_translate("MainWindow", "quit", None))
        self.actionHelp.setText(_translate("MainWindow", "help", None))
        self.actionPymol.setText(_translate("MainWindow", "pymol", None))
        self.actionPreference.setText(_translate("MainWindow", "preference", None))
        self.actionEmail_help.setText(_translate("MainWindow", "online_help", None))
        self.actionSASTBX.setText(_translate("MainWindow", "SASTBX Example", None))
        self.actionSASTBX.setIconText(_translate("MainWindow", "SASTBX", None))
        self.actionDocument.setText(_translate("MainWindow", "SASTBX Document", None))
        self.actionOpenProject.setText(_translate("MainWindow", "New Project", None))
        self.actionPymol_2.setText(_translate("MainWindow", "pymol", None))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

