# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pregxs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Pregxs(object):
    def setupUi(self, Pregxs):
        Pregxs.setObjectName(_fromUtf8("Pregxs"))
        Pregxs.resize(732, 629)
        Pregxs.setIconSize(QtCore.QSize(80, 80))
        self.centralwidget = QtGui.QWidget(Pregxs)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(4, 0))
        self.tabWidget.setSizeIncrement(QtCore.QSize(10000, 10000))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayout = QtGui.QFormLayout(self.tab_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_20 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_6.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_6.addWidget(self.label_21)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_7.addWidget(self.label)
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_7.addWidget(self.label_7)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.verticalLayout_7)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setMaximumSize(QtCore.QSize(50, 50))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/play.png")))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_14.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_14.addWidget(self.label_24)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setMaximumSize(QtCore.QSize(55, 55))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/help.png")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_13.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_16)
        spacerItem3 = QtGui.QSpacerItem(20, 210, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_17 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout.addWidget(self.label_18)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_19 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_7.addWidget(self.label_19)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.dat_lineEdit = QtGui.QLineEdit(self.tab)
        self.dat_lineEdit.setObjectName(_fromUtf8("dat_lineEdit"))
        self.horizontalLayout.addWidget(self.dat_lineEdit)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pregxs_saxs_showButton = QtGui.QPushButton(self.tab)
        self.pregxs_saxs_showButton.setObjectName(_fromUtf8("pregxs_saxs_showButton"))
        self.horizontalLayout.addWidget(self.pregxs_saxs_showButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dmax_lineEdit = QtGui.QLineEdit(self.tab)
        self.dmax_lineEdit.setObjectName(_fromUtf8("dmax_lineEdit"))
        self.horizontalLayout_2.addWidget(self.dmax_lineEdit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(19)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.scan_comboBox = QtGui.QComboBox(self.tab)
        self.scan_comboBox.setObjectName(_fromUtf8("scan_comboBox"))
        self.scan_comboBox.addItem(_fromUtf8(""))
        self.scan_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.scan_comboBox)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem19)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem21)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.textBrowser = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        Pregxs.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Pregxs)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Pregxs.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Pregxs)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Pregxs.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Pregxs)
        self.toolBar.setIconSize(QtCore.QSize(60, 60))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Pregxs.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtGui.QAction(Pregxs)
        self.actionQuit.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRun = QtGui.QAction(Pregxs)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon1)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionhelp = QtGui.QAction(Pregxs)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionhelp.setIcon(icon2)
        self.actionhelp.setObjectName(_fromUtf8("actionhelp"))
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionhelp)

        self.retranslateUi(Pregxs)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Pregxs)

    def retranslateUi(self, Pregxs):
        Pregxs.setWindowTitle(_translate("Pregxs", "SASTBX P(r) Estimation", None))
        self.label_20.setText(_translate("Pregxs", "P(r) Estimation", None))
        self.label_21.setText(_translate("Pregxs", "Pair_distance distribution function determination using Parametic Formula", None))
        self.label.setText(_translate("Pregxs", "Data:SAXS file, columns are q, intensity and sigma", None))
        self.label_6.setText(_translate("Pregxs", "Dmax:Maximum distance in particle", None))
        self.label_7.setText(_translate("Pregxs", "Scan:when True, a dmax scan will be performed, default False", None))
        self.label_24.setText(_translate("Pregxs", "Start the program", None))
        self.label_26.setText(_translate("Pregxs", "To obtain the example of  input and output files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Pregxs", "Introduction", None))
        self.label_17.setText(_translate("Pregxs", "P(r) Estimation", None))
        self.label_18.setText(_translate("Pregxs", "Pair_distance distribution function determination using Parametic Formula", None))
        self.label_19.setText(_translate("Pregxs", "SAXS profile", None))
        self.label_2.setText(_translate("Pregxs", "Data", None))
        self.pushButton.setText(_translate("Pregxs", "brower", None))
        self.pregxs_saxs_showButton.setText(_translate("Pregxs", "Show", None))
        self.label_3.setText(_translate("Pregxs", "Dmax", None))
        self.label_15.setText(_translate("Pregxs", "Optional", None))
        self.label_4.setText(_translate("Pregxs", "Scan Dmax", None))
        self.scan_comboBox.setItemText(0, _translate("Pregxs", "False", None))
        self.scan_comboBox.setItemText(1, _translate("Pregxs", "True", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Pregxs", "Input", None))
        self.label_5.setText(_translate("Pregxs", "Result", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Pregxs", "Output", None))
        self.toolBar.setWindowTitle(_translate("Pregxs", "toolBar", None))
        self.actionQuit.setText(_translate("Pregxs", "quit", None))
        self.actionRun.setText(_translate("Pregxs", "run", None))
        self.actionhelp.setText(_translate("Pregxs", "help", None))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Pregxs = QtGui.QMainWindow()
    ui = Ui_Pregxs()
    ui.setupUi(Pregxs)
    Pregxs.show()
    sys.exit(app.exec_())

