# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Superpose.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Superpose(object):
    def setupUi(self, Superpose):
        Superpose.setObjectName(_fromUtf8("Superpose"))
        Superpose.resize(732, 633)
        self.centralwidget = QtGui.QWidget(Superpose)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.superpose_tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        self.superpose_tabWidget.setFont(font)
        self.superpose_tabWidget.setObjectName(_fromUtf8("superpose_tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(30, 40, 241, 51))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 231, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 181, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 180, 441, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 230, 651, 108))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setMaximumSize(QtCore.QSize(50, 50))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/play.png")))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_14.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_14.addWidget(self.label_25)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.layoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 350, 651, 108))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_26 = QtGui.QLabel(self.layoutWidget_2)
        self.label_26.setMaximumSize(QtCore.QSize(55, 55))
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/help.png")))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(31, 11, 211, 33))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DecoType Naskh"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 481, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Gurmukhi MT"))
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.superpose_tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Superpose_name_label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Superpose_name_label.setFont(font)
        self.Superpose_name_label.setLineWidth(2)
        self.Superpose_name_label.setMidLineWidth(0)
        self.Superpose_name_label.setObjectName(_fromUtf8("Superpose_name_label"))
        self.horizontalLayout.addWidget(self.Superpose_name_label)
        spacerItem3 = QtGui.QSpacerItem(114, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(56, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(56, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem6 = QtGui.QSpacerItem(94, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.Superpose_index2_label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Chalkboard SE"))
        font.setPointSize(17)
        font.setItalic(True)
        self.Superpose_index2_label.setFont(font)
        self.Superpose_index2_label.setObjectName(_fromUtf8("Superpose_index2_label"))
        self.horizontalLayout_2.addWidget(self.Superpose_index2_label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtGui.QSpacerItem(56, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        spacerItem10 = QtGui.QSpacerItem(56, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(56, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Superpose_label1 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bodoni 72 Smallcaps"))
        font.setPointSize(19)
        self.Superpose_label1.setFont(font)
        self.Superpose_label1.setObjectName(_fromUtf8("Superpose_label1"))
        self.horizontalLayout_3.addWidget(self.Superpose_label1)
        self.Superpose_fix_lineEdit = QtGui.QLineEdit(self.tab)
        self.Superpose_fix_lineEdit.setObjectName(_fromUtf8("Superpose_fix_lineEdit"))
        self.horizontalLayout_3.addWidget(self.Superpose_fix_lineEdit)
        self.Superpose_fix_pushButton = QtGui.QPushButton(self.tab)
        self.Superpose_fix_pushButton.setObjectName(_fromUtf8("Superpose_fix_pushButton"))
        self.horizontalLayout_3.addWidget(self.Superpose_fix_pushButton)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Superpose_label2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bodoni 72 Smallcaps"))
        font.setPointSize(19)
        self.Superpose_label2.setFont(font)
        self.Superpose_label2.setObjectName(_fromUtf8("Superpose_label2"))
        self.horizontalLayout_4.addWidget(self.Superpose_label2)
        self.Superpose_mov_lineEdit = QtGui.QLineEdit(self.tab)
        self.Superpose_mov_lineEdit.setObjectName(_fromUtf8("Superpose_mov_lineEdit"))
        self.horizontalLayout_4.addWidget(self.Superpose_mov_lineEdit)
        self.Superpose_mov_pushButton = QtGui.QPushButton(self.tab)
        self.Superpose_mov_pushButton.setObjectName(_fromUtf8("Superpose_mov_pushButton"))
        self.horizontalLayout_4.addWidget(self.Superpose_mov_pushButton)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        spacerItem16 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem17)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.superpose_label3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Didot"))
        font.setPointSize(17)
        self.superpose_label3.setFont(font)
        self.superpose_label3.setObjectName(_fromUtf8("superpose_label3"))
        self.horizontalLayout_5.addWidget(self.superpose_label3)
        self.Superpose_nmax_comboBox = QtGui.QComboBox(self.tab)
        self.Superpose_nmax_comboBox.setObjectName(_fromUtf8("Superpose_nmax_comboBox"))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.Superpose_nmax_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.Superpose_nmax_comboBox)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.writemap_comboBox = QtGui.QComboBox(self.tab)
        self.writemap_comboBox.setObjectName(_fromUtf8("writemap_comboBox"))
        self.writemap_comboBox.addItem(_fromUtf8(""))
        self.writemap_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.writemap_comboBox)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem20)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem21)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.superpose_tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Baghdad"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.superpose_textBrowser = QtGui.QTextBrowser(self.tab2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Devanagari MT"))
        font.setPointSize(14)
        self.superpose_textBrowser.setFont(font)
        self.superpose_textBrowser.setObjectName(_fromUtf8("superpose_textBrowser"))
        self.verticalLayout.addWidget(self.superpose_textBrowser)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.superpose_tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.superpose_tabWidget)
        Superpose.setCentralWidget(self.centralwidget)
        self.superpose_statusbar = QtGui.QStatusBar(Superpose)
        self.superpose_statusbar.setObjectName(_fromUtf8("superpose_statusbar"))
        Superpose.setStatusBar(self.superpose_statusbar)
        self.superpose_toolBar = QtGui.QToolBar(Superpose)
        self.superpose_toolBar.setIconSize(QtCore.QSize(60, 60))
        self.superpose_toolBar.setObjectName(_fromUtf8("superpose_toolBar"))
        Superpose.addToolBar(QtCore.Qt.TopToolBarArea, self.superpose_toolBar)
        self.Superpose_actionQuit = QtGui.QAction(Superpose)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Superpose_actionQuit.setIcon(icon)
        self.Superpose_actionQuit.setObjectName(_fromUtf8("Superpose_actionQuit"))
        self.Superpose_actionRun = QtGui.QAction(Superpose)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Superpose_actionRun.setIcon(icon1)
        self.Superpose_actionRun.setObjectName(_fromUtf8("Superpose_actionRun"))
        self.Superpose_actionHelp = QtGui.QAction(Superpose)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Superpose_actionHelp.setIcon(icon2)
        self.Superpose_actionHelp.setObjectName(_fromUtf8("Superpose_actionHelp"))
        self.actionShow = QtGui.QAction(Superpose)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/imge/show.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionShow.setIcon(icon3)
        self.actionShow.setObjectName(_fromUtf8("actionShow"))
        self.superpose_toolBar.addAction(self.Superpose_actionQuit)
        self.superpose_toolBar.addAction(self.Superpose_actionRun)
        self.superpose_toolBar.addAction(self.Superpose_actionHelp)
        self.superpose_toolBar.addAction(self.actionShow)

        self.retranslateUi(Superpose)
        self.superpose_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Superpose)

    def retranslateUi(self, Superpose):
        Superpose.setWindowTitle(_translate("Superpose", "SASTBX Model Superposition", None))
        self.label_23.setText(_translate("Superpose", "Superpose models at low resolutions", None))
        self.label_4.setText(_translate("Superpose", "Model: objects to be superposed", None))
        self.label_5.setText(_translate("Superpose", "Optional control parameters:", None))
        self.label_6.setText(_translate("Superpose", "Nmax: maximum order of zernike polynomial:fixed for the existing", None))
        self.label_25.setText(_translate("Superpose", "Start the program", None))
        self.label_27.setText(_translate("Superpose", "To obtain the example of  input and output files", None))
        self.label_2.setText(_translate("Superpose", "Model Superposition", None))
        self.label_3.setText(_translate("Superpose", "Support molecular models in various format (PDB/ENT)", None))
        self.superpose_tabWidget.setTabText(self.superpose_tabWidget.indexOf(self.tab_2), _translate("Superpose", "Introduction", None))
        self.Superpose_name_label.setText(_translate("Superpose", "Model Superposition", None))
        self.Superpose_index2_label.setText(_translate("Superpose", "Superpose models at low resolutions", None))
        self.Superpose_label1.setText(_translate("Superpose", "Model A", None))
        self.Superpose_fix_pushButton.setText(_translate("Superpose", "Brower", None))
        self.Superpose_label2.setText(_translate("Superpose", "Model B", None))
        self.Superpose_mov_pushButton.setText(_translate("Superpose", "Brower", None))
        self.label_7.setText(_translate("Superpose", "We suggest to put high resolution model in A, and lower resolution model in B.", None))
        self.superpose_label3.setText(_translate("Superpose", "Nmax", None))
        self.Superpose_nmax_comboBox.setItemText(0, _translate("Superpose", "15", None))
        self.Superpose_nmax_comboBox.setItemText(1, _translate("Superpose", "16", None))
        self.Superpose_nmax_comboBox.setItemText(2, _translate("Superpose", "17", None))
        self.Superpose_nmax_comboBox.setItemText(3, _translate("Superpose", "18", None))
        self.Superpose_nmax_comboBox.setItemText(4, _translate("Superpose", "19", None))
        self.Superpose_nmax_comboBox.setItemText(5, _translate("Superpose", "20", None))
        self.Superpose_nmax_comboBox.setItemText(6, _translate("Superpose", "21", None))
        self.Superpose_nmax_comboBox.setItemText(7, _translate("Superpose", "22", None))
        self.Superpose_nmax_comboBox.setItemText(8, _translate("Superpose", "23", None))
        self.Superpose_nmax_comboBox.setItemText(9, _translate("Superpose", "24", None))
        self.Superpose_nmax_comboBox.setItemText(10, _translate("Superpose", "25", None))
        self.label_8.setText(_translate("Superpose", "write map", None))
        self.writemap_comboBox.setItemText(0, _translate("Superpose", "False", None))
        self.writemap_comboBox.setItemText(1, _translate("Superpose", "True", None))
        self.superpose_tabWidget.setTabText(self.superpose_tabWidget.indexOf(self.tab), _translate("Superpose", "Input", None))
        self.label.setText(_translate("Superpose", "Result", None))
        self.superpose_tabWidget.setTabText(self.superpose_tabWidget.indexOf(self.tab2), _translate("Superpose", "Output", None))
        self.superpose_toolBar.setWindowTitle(_translate("Superpose", "toolBar", None))
        self.Superpose_actionQuit.setText(_translate("Superpose", "quit", None))
        self.Superpose_actionRun.setText(_translate("Superpose", "Run", None))
        self.Superpose_actionHelp.setText(_translate("Superpose", "help", None))
        self.actionShow.setText(_translate("Superpose", "show maps in pymol", None))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Superpose = QtGui.QMainWindow()
    ui = Ui_Superpose()
    ui.setupUi(Superpose)
    Superpose.show()
    sys.exit(app.exec_())

